### ISSUE TITLE
Pet bonding

### ISSUE THREAD

**Issue by fhcilitator** [3HMonkey/DefianceUOR#30]
A tester reported that he does not get the option to bond his pet when he feeds it and stables it.   There no notification if this process is working or not.

**Comment by 3HMonkey** [comment]
It is already active, just without any message.
I updated the script and included a bond info where you'll be able to feed your pet to receive a message how much time is left until it is bonded. This is available after next restart.

`
if (IsBondable && !IsBonded)
                        {
                            var master = m_ControlMaster;

                            if (master != null && master == from) // So friends can't start the bonding process
                            {
                                if (MinTameSkill <= 29.1 || master.Skills.AnimalTaming.Base >= MinTameSkill ||
                                    OverrideBondingReqs() ||
                                    Core.ML && master.Skills.AnimalTaming.Value >= MinTameSkill)
                                {
                                    if (BondingBegin == DateTime.MinValue)
                                    {
                                        BondingBegin = Core.Now;
                                        from.SendMessage(0x38, "Your pet has begun bonding with you. Feed them again after 7 days from now to complete the bonding process.");

                                    }
                                    else if (BondingBegin + BondingDelay <= Core.Now)
                                    {
                                        IsBonded = true;
                                        BondingBegin = DateTime.MinValue;
                                        from.SendLocalizedMessage(1049666); // Your pet has bonded with you!
                                    }
                                    else // they are in the middle of the bonding process
                                    {
                                        DateTime today = Core.Now;
                                        DateTime willbebonded = BondingBegin.AddDays(7);
                                        TimeSpan bondedfor = BondingBegin - today;
                                        TimeSpan daystobond = willbebonded - today;
                                        string BondInfo = string.Format("The pet started bonding with you at {0}. Its {1} days, {2} hours and {3} minutes until it bonds", BondingBegin, daystobond.Days,
                                        daystobond.Hours, daystobond.Minutes);
                                        from.SendMessage(0x38, BondInfo);
                                    }
                                }
                                else if (Core.ML)
                                {
                                    from.SendLocalizedMessage(
                                        1075268
                                    ); // Your pet cannot form a bond with you until your animal taming ability has risen.
                                }
                            }
                        }
`
