### ISSUE TITLE
Inscribe stone not issuing materials

### ISSUE THREAD

**Issue by fhcilitator** [3HMonkey/DefianceUOR#31]
a new scribe reported that the stone will  not give him any materials . he has gm scribe / mage skills

**Comment by 3HMonkey** [comment]
It is not working because the amount of items in the bags. By the way we spawn bags now directly:
![grafik](https://user-images.githubusercontent.com/4610892/117249961-c3bdc300-ae42-11eb-96e0-7547afdc614a.png)
