### ISSUE TITLE
Taming range increase (2 tiles)

### ISSUE THREAD

**Issue by 3HMonkey** [3HMonkey/DefianceUOR#43]

**Comment by sage474** [comment]
Is this fixed because last test had it not working

**Comment by anthonyjrye** [comment]
I'm not sure this completely resolved since about 50% of the time i get a message that says you must cease taming because the path is not clear
Even though I'm just out of attack rang, and i have target paralyzed so it cant move.

**Comment by anthonyjrye** [comment]
Seems to be fixed, can tame 2 tiles away and not getting "taming ceased because there is no clear path to target." after paralyzing a target to tame.
