### ISSUE TITLE
Spawners

### ISSUE THREAD

**Issue by sage474** [3HMonkey/DefianceUOR#62]
some spawners (or all will test more locations) are not spawning mobs will go into the -time for the respawn
![unknown](https://user-images.githubusercontent.com/87563551/126911574-69b6dba4-0b99-45b0-9a32-2c56042bd906.png)
![unknowssn](https://user-images.githubusercontent.com/87563551/126911579-e05a14d0-6c85-4174-a8b4-1f073a796008.png)

**Comment by kamronbatman** [comment]
I saw this in ModernUO. Might be related to timer wheel. I'll look into it when I get some time.
If you can reproduce it let me know.

**Comment by sage474** [comment]
That's 2 different spawners

**Comment by kamronbatman** [comment]
Fixed in ModernUO, @3HMonkey will update Defiance.
