### ISSUE TITLE
Meditation failure

### ISSUE THREAD

**Issue by borchUO** [3HMonkey/DefianceUOR#69]
-meditation fails a lot being GM, noticed it under fight, being targetted by mobs

**Comment by 3HMonkey** [comment]
Interrupted or not?

**Comment by borchUO** [comment]
when I say it fails, I mean that it says "You cannot focus your concentration".

![image](https://user-images.githubusercontent.com/88916398/129908817-126fd5de-b328-4ded-bc70-6c547176bd00.png)

**Comment by sage474** [comment]
What armor are you wearing if any

**Comment by borchUO** [comment]
> What armor are you wearing if any

none

**Comment by 3HMonkey** [comment]
Original formula is:
`var skillVal = m.Skills.Meditation.Value;
            var chance = (50.0 + (skillVal - (m.ManaMax - m.Mana)) * 2) / 100;`

while this is commented out on DFI => I'll fix this UOR like

**Comment by 3HMonkey** [comment]
done!
