### ISSUE TITLE
Terathan Spawn

### ISSUE THREAD

**Issue by borchUO** [3HMonkey/DefianceUOR#72]
10 spots in which spawn the same pack of mobs.
1x Balron
1x Dragon
1x Drake
1x Nightmare
1x Terathan of each type
1x ophidian of each type

This configuration makes no sense, goes against the lore of the dungeon, and discredits other dungeons.

![image](https://user-images.githubusercontent.com/88916398/129950058-1c0871e7-e732-4b11-9241-08c84843e64c.png)
![image](https://user-images.githubusercontent.com/88916398/129950064-c2c5606a-2cbc-44ec-974f-343f2461eac3.png)
![image](https://user-images.githubusercontent.com/88916398/129950075-bebc639f-e7d9-41ef-8ec0-e8d8586409f5.png)
![image](https://user-images.githubusercontent.com/88916398/129950086-52af0f9b-bf16-419d-907e-ecbc133312f1.png)
![image](https://user-images.githubusercontent.com/88916398/129950091-9472adca-e3bb-4adc-8f4d-0185b2ae4bfd.png)
![image](https://user-images.githubusercontent.com/88916398/129950102-8f5d0fc1-8aea-4dda-a6f9-4ade61120f0e.png)
![image](https://user-images.githubusercontent.com/88916398/129950116-a6d838f7-84c9-44d2-b0e1-8c50df4bb678.png)
![image](https://user-images.githubusercontent.com/88916398/129950129-a8a84c5b-ec71-4c94-b9a3-cffce269a7fb.png)
![image](https://user-images.githubusercontent.com/88916398/129950139-aa74ce1c-d553-4b23-bd65-60a7e5019c2c.png)
![image](https://user-images.githubusercontent.com/88916398/129950156-a081ff38-ed24-4d6d-bae0-92801b6b6b3a.png)

**Comment by sage474** [comment]
Will look into adjusting the spawns ty
