### ISSUE TITLE
Incorrect starting skill numbers (bald reported)

### ISSUE THREAD

**Issue by fhcilitator** [3HMonkey/DefianceUOR#75]
Bald created a rouge character with some skills set in char creation.  He noticed that his remove trap did not set to the amount indicated.  His char create with 0 remove trap skill and it was supposed to be 40+.

**Comment by anthonyjrye** [comment]
This is still an issue with remove trap skill just created a char by the name of deletemeone i tried remove trap, item id, camping,. and cooking remove trap was the only skill that didn't  the rest got 30 points. Going to check again with deletemetwo and see if same result as I didn't double check amount set but i believe it was somewhere around 30 is. not sure

**Comment by anthonyjrye** [comment]
Deletemetwo
Just verified character starting stat remove trap doesn't get set. Verified Forensics,, Fishing, Herding, all set to 30 accept remove trap
Remove trap remains unchanged with setting of 0.0 after using show real in the skills ui on both deletemeone and deletemetwo

**Comment by kamronbatman** [comment]
This is the correct behavior. I believe you are not supposed to be able to select it, but because we are using a new client, the remainder of the skills are available.
I'll do some research into this, meanwhile @3HMonkey can unblock RemoveTrap if he wants. I sent him instructions.

**Comment by 3HMonkey** [comment]
Thx guys. It will be fixed with next patch/restart.

**Comment by anthonyjrye** [comment]
That's fine I don't recall precisely what I remember for certain is that you had to pay for for stealth training.  There is no rogue trainer in Brit Ill had screenshot of where I think i remember it should be.  I believe it got moved to new haven
