### ISSUE TITLE
Missing npc spawns in major towns

### ISSUE THREAD

**Issue by anthonyjrye** [3HMonkey/DefianceUOR#81]
screen shots of missing or possible missing npcs to the best of my recollection

**Comment by anthonyjrye** [comment]
Brit
![screenshot_2021-08-25_10-36-07](https://user-images.githubusercontent.com/20714046/131198733-2b47fbdb-26ba-4810-80f4-77fa4b04e402.png)
![screenshot_2021-08-27_03-32-46](https://user-images.githubusercontent.com/20714046/131198741-80f79e89-a923-4ec6-a61f-71234580d2b1.png)
![screenshot_2021-08-27_03-41-08](https://user-images.githubusercontent.com/20714046/131198759-bdfb20d9-dacd-4c74-892c-51bc26a0533d.png)
![screenshot_2021-08-27_03-41-47](https://user-images.githubusercontent.com/20714046/131198765-c96ee62b-6975-411f-a379-243595b51a7c.png)
![screenshot_2021-08-27_03-44-01](https://user-images.githubusercontent.com/20714046/131198767-8acabb85-d3e9-4d28-8086-0219b6678ade.png)
![screenshot_2021-08-27_03-44-47](https://user-images.githubusercontent.com/20714046/131198770-9bbd04fa-3627-49a4-89a0-075b5b023f72.png)
![screenshot_2021-08-27_03-46-34](https://user-images.githubusercontent.com/20714046/131198772-1292e71c-51fc-43a4-908d-a68c807daace.png)
![screenshot_2021-08-27_03-52-29](https://user-images.githubusercontent.com/20714046/131198776-c3a554a7-60fe-4fc6-829d-c424d5ebca7c.png)

Cove
![screenshot_2021-08-27_03-54-48](https://user-images.githubusercontent.com/20714046/131198812-0545b61a-652b-461f-a173-f01719ee31ac.png)

Jhelom
![screenshot_2021-08-27_04-07-09](https://user-images.githubusercontent.com/20714046/131198841-4c800e22-20fa-4822-904e-7dbb07
![screenshot_2021-08-27_06-32-06](https://user-images.githubusercontent.com/20714046/131199023-6bafe95e-2727-4592-be27-ef88ed90517b.png)
![screenshot_2021-08-27_06-34-52](https://user-images.githubusercontent.com/20714046/131199024-8d2468c1-6ba3-498d-9de5-a21a5dfd77f0.png)
4f1add.png)
![screenshot_2021-08-27_04-07-32](https://user-images.githubusercontent.com/20714046/131198845-02d109ed-627c-4f97-8fdc-220bae58b071.png)
![screenshot_2021-08-27_04-09-35](https://user-images.githubusercontent.com/20714046/131198847-ad900825-4542-44f8-8d87-2f61339d3cb7.png)
![screenshot_2021-08-27_04-11-31](https://user-images.githubusercontent.com/20714046/131198849-125e1055-217d-4085-adec-133d92fbccf3.png)

Moonglow
![screenshot_2021-08-27_05-12-34](https://user-images.githubusercontent.com/20714046/131198879-cbcaf555-9ecb-4cd1-ad3b-e5710d161af8.png)
![screenshot_2021-08-27_05-14-33](https://user-images.githubusercontent.com/20714046/131198881-8c35e86b-1044-463a-987e-a9a09d8a08b0.png)
![screenshot_2021-08-27_05-19-28](https://user-images.githubusercontent.com/20714046/131198885-3d8adfe2-39e8-4e89-9108-4628bd49a6f9.png)
![screenshot_2021-08-27_05-22-52](https://user-images.githubusercontent.com/20714046/131198888-7b1f7934-aba9-479a-80b1-c9d065b514c4.png)
![screenshot_2021-08-27_05-22-59](https://user-images.githubusercontent.com/20714046/131198892-196795d7-8905-48f6-a9a9-2c4a0e7b8edd.png)

New Magincia
![screenshot_2021-08-27_05-27-13](https://user-images.githubusercontent.com/20714046/131198928-c4b0e354-e05f-49f3-a9c6-56453c461174.png)
![screenshot_2021-08-27_05-27-21](https://user-images.githubusercontent.com/20714046/131198930-e8ae462f-7305-46e0-949c-cdc75a51920c.png)
![screenshot_2021-08-27_05-28-16](https://user-images.githubusercontent.com/20714046/131198933-54cc20ef-8295-4210-bd8f-831e891993b8.png)
![screenshot_2021-08-27_05-28-45](https://user-images.githubusercontent.com/20714046/131198935-c6cff849-6a33-49c4-9349-d1479dd10815.png)
![screenshot_2021-08-27_05-29-12](https://user-images.githubusercontent.com/20714046/131198939-04a6086e-ac60-46d4-b7e1-ec39078fb4fd.png)
![screenshot_2021-08-27_05-29-58](https://user-images.githubusercontent.com/20714046/131198941-f3324a4f-d453-4f35-a425-62e55df3c971.png)
![screenshot_2021-08-27_05-30-45](https://user-images.githubusercontent.com/20714046/131198943-ae9afc0c-d831-4b45-b438-cf2ba96c89b8.png)

Skara Brae
![screenshot_2021-08-27_05-37-13](https://user-images.githubusercontent.com/20714046/131198979-663d8f8d-5686-4195-8e4b-857e1d36b30f.png)
![screenshot_2021-08-27_05-37-57](https://user-images.githubusercontent.com/20714046/131198981-dd00935b-9dde-4d9d-b97a-224a65d2c43f.png)
![screenshot_2021-08-27_05-38-23](https://user-images.githubusercontent.com/20714046/131198983-0f2a300d-2445-4ff5-8f29-4e0912f2c2c8.png)
![screenshot_2021-08-27_05-38-31](https://user-images.githubusercontent.com/20714046/131198985-ba9fe13d-8b58-4066-8663-b200dcbd8516.png)
![screenshot_2021-08-27_05-39-09](https://user-images.githubusercontent.com/20714046/131198989-08a826e7-35ac-4614-a5c4-5726f300783c.png)
![screenshot_2021-08-27_05-40-32](https://user-images.githubusercontent.com/20714046/131198992-ea8d9a75-3a5b-475c-be73-4718c9b17180.png)

Yew
![screenshot_2021-08-27_06-22-52](https://user-images.githubusercontent.com/20714046/131199011-6ac0c413-0df6-46e7-86bb-58f837f19e33.png)
![screenshot_2021-08-27_06-23-31](https://user-images.githubusercontent.com/20714046/131199016-c79c7440-ec67-4b48-8901-6df88ed01702.png)
![screenshot_2021-08-27_06-30-34](https://user-images.githubusercontent.com/20714046/131199019-72345a44-e884-4e58-8092-664082e846b4.png)

**Comment by anthonyjrye** [comment]
Brit
![screenshot_2021-08-27_03-32-46](https://user-images.githubusercontent.com/20714046/131199137-aa3e6570-4036-413f-a13e-2ba932c53e25.png)
![screenshot_2021-08-27_03-41-08](https://user-images.githubusercontent.com/20714046/131199143-a3502d8b-db9b-4146-8197-7ef297a77c58.png)
![screenshot_2021-08-27_03-41-47](https://user-images.githubusercontent.com/20714046/131199145-18fe5247-c47c-4b97-bd4d-dc3310d1f18b.png)
![screenshot_2021-08-27_03-44-01](https://user-images.githubusercontent.com/20714046/131199148-ce17ff89-25a2-4cd5-af5e-cfd988374e77.png)
![screenshot_2021-08-27_03-44-47](https://user-images.githubusercontent.com/20714046/131199149-8757c927-f9b8-4dca-8dd5-e56ff2692622.png)
![screenshot_2021-08-27_03-46-34](https://user-images.githubusercontent.com/20714046/131199152-f8d61ab7-4c4e-4546-9baf-1dd9439881a0.png)
![screenshot_2021-08-27_03-52-29](https://user-images.githubusercontent.com/20714046/131199155-569180a7-8e5d-4689-adec-c5e1158d3bbb.png)

Cove 
![screenshot_2021-08-27_03-54-48](https://user-images.githubusercontent.com/20714046/131199192-4b3d1317-5bc0-41d7-94c4-043df50ea85c.png)

Jhelom
![screenshot_2021-08-27_04-07-09](https://user-images.githubusercontent.com/20714046/131199214-82e5c66b-3546-453d-8664-1ae328865201.png)
![screenshot_2021-08-27_04-07-32](https://user-images.githubusercontent.com/20714046/131199218-8bf0cef3-bd71-4d06-8f56-a7b6713dca13.png)
![screenshot_2021-08-27_04-09-35](https://user-images.githubusercontent.com/20714046/131199219-019149ee-ea6b-44d9-a653-8782350825b0.png)

Moonglow
![screenshot_2021-08-27_05-12-34](https://user-images.githubusercontent.com/20714046/131199256-56def31f-a323-44d3-9fda-1d5d2b450ffa.png)
![screenshot_2021-08-27_05-14-33](https://user-images.githubusercontent.com/20714046/131199262-520d41db-3bfe-457b-9c45-77a516aa35df.png)
![screenshot_2021-08-27_05-19-28](https://user-images.githubusercontent.com/20714046/131199263-03baa21f-6207-42c7-abcd-0195ad2bf987.png)
![screenshot_2021-08-27_05-22-52](https://user-images.githubusercontent.com/20714046/131199265-f3668798-f9c0-418e-96ba-a95e5cd730fd.png)
![screenshot_2021-08-27_05-22-59](https://user-images.githubusercontent.com/20714046/131199269-7fc068b0-1f9a-438a-b26f-1f96f3f8664d.png)

New Magincia
![screenshot_2021-08-27_05-27-13](https://user-images.githubusercontent.com/20714046/131199300-ff4e1342-6496-431d-b525-51adb1ed087b.png)
![screenshot_2021-08-27_05-27-21](https://user-images.githubusercontent.com/20714046/131199304-210e9200-eda0-4246-8068-31a17bf4528b.png)
![screenshot_2021-08-27_05-28-16](https://user-images.githubusercontent.com/20714046/131199308-54098565-907e-48e5-98ac-9dae82cf0265.png)
![screenshot_2021-08-27_05-28-45](https://user-images.githubusercontent.com/20714046/131199311-e3558744-cca4-4470-9cbc-e8f135b7e019.png)
![screenshot_2021-08-27_05-29-12](https://user-images.githubusercontent.com/20714046/131199312-46768372-9cbd-4bc1-9eed-544e47f1746d.png)
![screenshot_2021-08-27_05-29-58](https://user-images.githubusercontent.com/20714046/131199313-c9328599-a4a9-4700-afa8-f632e82bebbd.png)
![screenshot_2021-08-27_05-30-45](https://user-images.githubusercontent.com/20714046/131199318-71ca75a3-6fc1-4afb-8692-192f6bbcbe4b.png)

Skara Brae
![screenshot_2021-08-27_05-37-13](https://user-images.githubusercontent.com/20714046/131199351-18e49395-36fb-48a4-b85c-3984add6493f.png)
![screenshot_2021-08-27_05-37-57](https://user-images.githubusercontent.com/20714046/131199356-668f0348-71e0-4920-a33a-f65931412871.png)
![screenshot_2021-08-27_05-38-23](https://user-images.githubusercontent.com/20714046/131199359-22dd84d5-2273-4fbc-a90b-4034f5346da8.png)
![screenshot_2021-08-27_05-38-31](https://user-images.githubusercontent.com/20714046/131199362-445fcf96-f255-4312-9fce-43fe7f66e450.png)
![screenshot_2021-08-27_05-39-09](https://user-images.githubusercontent.com/20714046/131199365-c105cd25-8b76-4b8d-b224-41ee462de68e.png)
![screenshot_2021-08-27_05-40-32](https://user-images.githubusercontent.com/20714046/131199369-213fc0fc-7896-4434-b6d2-8c953f5e6f24.png)

Trinsic
![screenshot_2021-08-27_05-44-06](https://user-images.githubusercontent.com/20714046/131199403-3f8c3bae-959e-47f4-96d4-4bbe19e387d5.png)
![screenshot_2021-08-27_05-45-17](https://user-images.githubusercontent.com/20714046/131199409-e6f8317a-28e9-4f9f-b544-4564a1df3e8b.png)
![screenshot_2021-08-27_05-46-23](https://user-images.githubusercontent.com/20714046/131199412-9492e336-df85-4f2b-b4d4-166d47724340.png)

Vesper
![screenshot_2021-08-27_06-05-47](https://user-images.githubusercontent.com/20714046/131199435-5b3c83f2-c3cb-4947-af23-0ffe024e9492.png)
![screenshot_2021-08-27_06-05-59](https://user-images.githubusercontent.com/20714046/131199438-9b6f503e-ecf1-45e2-a7cb-2f1e4b5b30bd.png)
![screenshot_2021-08-27_06-06-35](https://user-images.githubusercontent.com/20714046/131199441-424d469a-6994-4fb4-adb2-b7268086e6e0.png)
![screenshot_2021-08-27_06-11-04](https://user-images.githubusercontent.com/20714046/131199443-e333271b-8021-4099-b914-42becdc125a1.png)
![screenshot_2021-08-27_06-11-08](https://user-images.githubusercontent.com/20714046/131199447-1f5501d0-94b0-4ba6-916b-a87ef4ac5a78.png)
![screenshot_2021-08-27_06-11-57](https://user-images.githubusercontent.com/20714046/131199451-554644a2-e024-4f0e-846c-d10d01615b66.png)
![screenshot_2021-08-27_06-12-00](https://user-images.githubusercontent.com/20714046/131199456-7ac69109-9a6f-45fe-9817-470dfe095a09.png)
![screenshot_2021-08-27_06-12-04](https://user-images.githubusercontent.com/20714046/131199457-bf5a976d-165c-4ed2-bc8c-57c4a437bcdb.png)
![screenshot_2021-08-27_06-13-05](https://user-images.githubusercontent.com/20714046/131199460-93a5307a-b3ae-4148-a570-0da1663a1268.png)

Yew
![screenshot_2021-08-27_06-22-52](https://user-images.githubusercontent.com/20714046/131199480-fb98bad0-0b98-44f7-9fe0-6642fb4974f7.png)
![screenshot_2021-08-27_06-23-31](https://user-images.githubusercontent.com/20714046/131199482-195290d6-95a4-4319-bde1-97fc089c7da2.png)
![screenshot_2021-08-27_06-30-34](https://user-images.githubusercontent.com/20714046/131199484-31406904-7c79-459b-8a25-6bd1a3f30c39.png)
![screenshot_2021-08-27_06-32-06](https://user-images.githubusercontent.com/20714046/131199486-79e433ae-0ecf-4ea7-9aa4-8abd72a5e445.png)
![screenshot_2021-08-27_06-34-52](https://user-images.githubusercontent.com/20714046/131199487-b039406d-6698-4228-9eaa-762e61dbd37e.png)

**Comment by anthonyjrye** [comment]
Forgot there should be a rogue trainer in Brit by West Bank
![image](https://user-images.githubusercontent.com/20714046/131220988-593de4e6-07fc-4c52-a72c-ec9ab376f6ec.png)

**Comment by sage474** [comment]
dm me top to bottom in order for what npcs go in these locations

**Comment by anthonyjrye** [comment]
Haven't ran across towns without npc/s think this is taken care of closing
